### PR TITLE
Optional param before required

### PR DESCRIPTION
**Pull request by jobjen02**
An optional parameter must be defined after the required parameters. This has been required since php 8.1.
Due to this issue we encountered a PHP error.

See:
https://arc.net/l/quote/xqkamcmp

### CODE REVIEW

**Comment by jobjen02** [comment]
Is someone able to pickup this small update?

**Review by WoutervanderLoopNL — APPROVED** [review]
Great :+1:

**Comment by WoutervanderLoopNL** [comment]
@casperbakker

**Comment by casperbakker** [comment]
Weird that our code does not complain about this, because we use PHP 8.3 for a while. But thanks for fixing.

**Pull request merged**
