### PR TITLE
Update Bol.com API to v6

### PR DESCRIPTION
**Pull request by frrrht**
This PR was made based on the PHPUnit test results.

### CODE REVIEW

**Comment by WoutervanderLoopNL** [comment]
Any update on this?

**Comment by bartvc** [comment]
Yes, I would like to know the same. Will there be a v6 version on time? Since v5 will be EOL on 01-11-22.

**Comment by bramstroker** [comment]
I am also interested in support for the new API versions.

**Comment by appdezign** [comment]
> Yes, I would like to know the same. Will there be a v6 version on time? Since v5 will be EOL on 01-11-22.

According to this link, v5 will be EOL on 01-10-22(!), which is in 9 weeks ...
I would really like to know if there will be support for the new versions.

[https://partnerplatform.bol.com/nl/hulp-nodig/automatiseren/wat-is-de-retailer-api-lifecycle-precies/](url)

**Comment by frrrht** [comment]
> > Yes, I would like to know the same. Will there be a v6 version on time? Since v5 will be EOL on 01-11-22.
> 
> According to this link, v5 will be EOL on 01-10-22(!), which is in 9 weeks ... I would really like to know if there will be support for the new versions.
> 
> [https://partnerplatform.bol.com/nl/hulp-nodig/automatiseren/wat-is-de-retailer-api-lifecycle-precies/](url)

I agree, I'll be working on a more thorough implementation of this V6 software. I assumed my PR (that passed the PHPUnit tests) would have made it easier for the Picqer team to review but during the span of this week I'll be implementing the V6 version in my codebase and verify everything's working. I haven't used every single endpoint yet in the Retailer API but will come back to this later with a verdict based on my own codebase. :)

**Comment by bartvc** [comment]
Ik ben afwezig t/m maandag 22 augustus.
Voor dringende zaken kunt u mailen naar: ***@***.*** .

**Comment by liamseys** [comment]
Can we get this merged please? @casperbakker

**Comment by bartvc** [comment]
Ik ben afwezig t/m maandag 22 augustus.
Voor dringende zaken kunt u mailen naar: ***@***.*** .

**Comment by bartvc** [comment]
Ik ben afwezig t/m maandag 22 augustus.
Voor dringende zaken kunt u mailen naar: ***@***.*** .

**Pull request merged**
