### PR TITLE
Add export to offer

### PR DESCRIPTION
**Pull request by sirajea**
Offers can be exported to a CSV file

### CODE REVIEW

**Comment by kleiram** [comment]
Hi there!

Thank you for your contribution! Would it be possible to add an example? Either in the `examples` directory or the PR body is fine for me. That way I can kind of grok how this should work.

**Comment by klaaskox** [comment]
> Hi there!
> 
> Thank you for your contribution! Would it be possible to add an example? Either in the `examples` directory or the PR body is fine for me. That way I can kind of grok how this should work.

This should work:

```
$exportRequest = Picqer\BolRetailer\Offer::export();
$exportRequest->waitUntilComplete();

try {
	$csv = Picqer\BolRetailer\Offer::getExport($exportRequest->entityId);
	echo $csv;
	
} catch (Exception $e) {
	echo $e->getMessage();
}
```

**Comment by thijsdejong** [comment]
@kleiram Hey! Could you please consider merging this? Would be quite useful!

**Comment by MartijnOud** [comment]
Thanks, this was exactly what I was looking for! Would be great if it gets merged.

**Comment by kleiram** [comment]
Looks good, I'm going to merge this. @sirajea Thanks for this contribution!

**Comment by kleiram** [comment]
@MartijnOud @thijsdejong I just merged and [released](https://github.com/picqer/bol-retailer-php-client/releases/tag/v1.2.0) this so it's available to use!

**Pull request merged**
